// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHyv_qf_cW1saoJD5nxpeox-oEvwotDCI',
    appId: '1:555414761934:web:526987756d767550bf7b9f',
    messagingSenderId: '555414761934',
    projectId: 'maps-app-392819',
    authDomain: 'maps-app-392819.firebaseapp.com',
    storageBucket: 'maps-app-392819.appspot.com',
    measurementId: 'G-QRQ3T88B7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKJO-WxKNt-PM4SAb1C2ukWGW5W4t3mVg',
    appId: '1:555414761934:android:d2058ae6c41cb292bf7b9f',
    messagingSenderId: '555414761934',
    projectId: 'maps-app-392819',
    storageBucket: 'maps-app-392819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbCjYZPma4KYxDSPTCwNcQ4xzfM772aDc',
    appId: '1:555414761934:ios:7946e183a03ab492bf7b9f',
    messagingSenderId: '555414761934',
    projectId: 'maps-app-392819',
    storageBucket: 'maps-app-392819.appspot.com',
    iosBundleId: 'com.example.mapsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbCjYZPma4KYxDSPTCwNcQ4xzfM772aDc',
    appId: '1:555414761934:ios:ebc8a50766683378bf7b9f',
    messagingSenderId: '555414761934',
    projectId: 'maps-app-392819',
    storageBucket: 'maps-app-392819.appspot.com',
    iosBundleId: 'com.example.mapsApp.RunnerTests',
  );
}
